apiVersion: v1
kind: Service
metadata:
  name: {{ include "settld.fullname" . }}-api
  labels:
    {{- include "settld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "settld.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api

