{{- if .Values.config.exportDestinationsJson }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "settld.fullname" . }}-config
  labels:
    {{- include "settld.labels" . | nindent 4 }}
data:
  PROXY_EXPORT_DESTINATIONS: {{ .Values.config.exportDestinationsJson | quote }}
{{- end }}

